In [13]:
import numpy as np
import pandas as pd

In [14]:

keep = {
  'name': ['Alice', 'Bob', 'Charlie'],
  'age': [25, 30, 35],
  'city': ['New York', 'Los Angeles', 'Chicago'],
  'salary': [70000, 80000, 90000]
}
df = pd.DataFrame(keep)
df

      name  age         city  salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000

In [15]:
# creating dataframe using list of lists
data_2 = [['Alice', 25, 'New York', 70000],
          ['Bob', 30, 'Los Angeles', 80000],        
          ['Charlie', 35, 'Chicago', 90000]]              

df = pd.DataFrame(data_2, columns=['name', 'age', 'city', 'salary'])
df

      name  age         city  salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000

In [16]:
# selection and indexing of columns
df[['name','city']]

      name         city
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago

In [17]:
# creating a column
df['role'] = ['Engineer', 'Manager', 'Analyst']
df

      name  age         city  salary      role
0    Alice   25     New York   70000  Engineer
1      Bob   30  Los Angeles   80000   Manager
2  Charlie   35      Chicago   90000   Analyst

In [18]:
# removing a column
df = df.drop(['city'], axis=1)

In [19]:
print(df)

      name  age  salary      role
0    Alice   25   70000  Engineer
1      Bob   30   80000   Manager
2  Charlie   35   90000   Analyst

In [20]:
# selecting rows
df.iloc[0]['name']

'Alice'

In [21]:
# selecting subset of rows and columns
df.loc[[0,1]][['name','salary']]

    name  salary
0  Alice   70000
1    Bob   80000

In [22]:
df.loc[[1,2]][['name','age']]

      name  age
1      Bob   30
2  Charlie   35

In [23]:
# conditional selection
df[(df['age']>30) & (df['role']=='Analyst')]

      name  age  salary     role
2  Charlie   35   90000  Analyst

In [24]:
df[(df['age']>30) | (df['role']=='Manager')]

      name  age  salary     role
1      Bob   30   80000  Manager
2  Charlie   35   90000  Analyst

In [25]:
# finding missing data
data = {
  'A':[1,2,np.nan,4,5],
  'B':[np.nan,2,3,4,5],
  'C':[1,2,3,np.nan,np.nan],
  'D':[1,np.nan,np.nan,np.nan,5]
}

df = pd.DataFrame(data)

In [29]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [30]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [28]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [31]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [32]:
# removing missing data
df.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [ ]:
df.dropna(thresh=3) # thresh: indicate there is in row atleast these much or more value should be non null, row with less value than thresh is removed

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

In [36]:
# filling the missing data
df.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [37]:
values = {'A':10,'B':20,'C':30,'D':40}
df.fillna(value=values)

      A     B     C     D
0   1.0  20.0   1.0   1.0
1   2.0   2.0   2.0  40.0
2  10.0   3.0   3.0  40.0
3   4.0   4.0  30.0  40.0
4   5.0   5.0  30.0   5.0

In [38]:
# dropna = row wise droping
# fillna = column wise filling

In [39]:
df.fillna(df.mean())

     A    B    C    D
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0

In [40]:
# merging, joining and concatenation
employee = pd.DataFrame({
  'employee_id':[1,2,3,4,5],
  'name':['avi','arth','arthur','vans','vanzola'],
  'department':['IT','Finance','Gaming','Development','Designing']
})

salaries = pd.DataFrame({
  'employee_id':[1,2,3,6,7],
  'salary':[60000,40000,5000,4622,455],
  'bonus':[1,2,5,6,8]
})

In [41]:
employee

   employee_id     name   department
0            1      avi           IT
1            2     arth      Finance
2            3   arthur       Gaming
3            4     vans  Development
4            5  vanzola    Designing

In [42]:
salaries

   employee_id  salary  bonus
0            1   60000      1
1            2   40000      2
2            3    5000      5
3            6    4622      6
4            7     455      8

In [51]:
pd.merge(employee, salaries, on='employee_id',how='outer') #on = common column in both , how = which join you want to use

   employee_id     name   department   salary  bonus
0            1      avi           IT  60000.0    1.0
1            2     arth      Finance  40000.0    2.0
2            3   arthur       Gaming   5000.0    5.0
3            4     vans  Development      NaN    NaN
4            5  vanzola    Designing      NaN    NaN
5            6      NaN          NaN   4622.0    6.0
6            7      NaN          NaN    455.0    8.0

In [52]:
pd.merge(employee, salaries, on='employee_id',how='left')

   employee_id     name   department   salary  bonus
0            1      avi           IT  60000.0    1.0
1            2     arth      Finance  40000.0    2.0
2            3   arthur       Gaming   5000.0    5.0
3            4     vans  Development      NaN    NaN
4            5  vanzola    Designing      NaN    NaN

In [53]:
pd.merge(employee, salaries, on='employee_id',how='right')

   employee_id    name department  salary  bonus
0            1     avi         IT   60000      1
1            2    arth    Finance   40000      2
2            3  arthur     Gaming    5000      5
3            6     NaN        NaN    4622      6
4            7     NaN        NaN     455      8

In [54]:
# concatination of 2 dataframes
df1 = pd.DataFrame({
  'A':['A0','A1','A2'],
  'B':['B0','B1','B2'],
  'C':['C0','C1','C2'],
})

df2 = pd.DataFrame({
  'A':['A3','A4','A5'],
  'B':['B3','B4','B5'],
  'C':['C3','C4','C5'],
})

In [56]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [57]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [61]:
pd.concat([df1,df2],ignore_index=True)

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3
4  A4  B4  C4
5  A5  B5  C5

In [62]:
pd.concat([df2,df1],ignore_index=True)

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
3  A0  B0  C0
4  A1  B1  C1
5  A2  B2  C2

In [63]:
pd.concat([df1,df2],ignore_index=True, axis=1)

    0   1   2   3   4   5
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [ ]:
# if we want to merge two dataframe based on column then we use merge
# if we want to concat two dataframe based on column or row then we use concat

In [64]:
# joining two data frames
df1 = pd.DataFrame({
  'name':['alice','bob','charlie']
}, index=[1,2,3])


df2 = pd.DataFrame({
  'score':[80,60,90]
}, index=[2,3,4])

In [65]:
df1

      name
1    alice
2      bob
3  charlie

In [66]:
df2

   score
2     80
3     60
4     90

In [71]:
df1.join(df2,how='outer')

      name  score
1    alice    NaN
2      bob   80.0
3  charlie   60.0
4      NaN   90.0