In [78]:
import numpy as np
import pandas as pd

In [79]:

keep = {
  'name': ['Alice', 'Bob', 'Charlie'],
  'age': [25, 30, 35],
  'city': ['New York', 'Los Angeles', 'Chicago'],
  'salary': [70000, 80000, 90000]
}
df = pd.DataFrame(keep)
df

      name  age         city  salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000

In [80]:
# creating dataframe using list of lists
data_2 = [['Alice', 25, 'New York', 70000],
          ['Bob', 30, 'Los Angeles', 80000],        
          ['Charlie', 35, 'Chicago', 90000]]              

df = pd.DataFrame(data_2, columns=['name', 'age', 'city', 'salary'])
df

      name  age         city  salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000

In [81]:
# selection and indexing of columns
df[['name','city']]

      name         city
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago

In [82]:
# creating a column
df['role'] = ['Engineer', 'Manager', 'Analyst']
df

      name  age         city  salary      role
0    Alice   25     New York   70000  Engineer
1      Bob   30  Los Angeles   80000   Manager
2  Charlie   35      Chicago   90000   Analyst

In [83]:
# removing a column
df = df.drop(['city','salary'], axis=1)

In [84]:
print(df)

      name  age      role
0    Alice   25  Engineer
1      Bob   30   Manager
2  Charlie   35   Analyst