In [5]:
import pandas as pd
import json
from io import StringIO
json_data = '{"employee_name":"james","job_type":"Software Engineer","salary":85000,"department":"Engineering","experience_years":5}'
# parse into a single-row DataFrame
df = pd.DataFrame([json.loads(json_data)])
df

  employee_name           job_type  salary   department  experience_years
0         james  Software Engineer   85000  Engineering                 5

In [6]:
df.to_json()

'{"employee_name":{"0":"james"},"job_type":{"0":"Software Engineer"},"salary":{"0":85000},"department":{"0":"Engineering"},"experience_years":{"0":5}}'

In [7]:
df.to_json(orient='records')

'[{"employee_name":"james","job_type":"Software Engineer","salary":85000,"department":"Engineering","experience_years":5}]'

In [8]:
df.to_json(orient='index')

'{"0":{"employee_name":"james","job_type":"Software Engineer","salary":85000,"department":"Engineering","experience_years":5}}'

In [10]:
df = pd.read_csv('wine.csv',header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,NaN,0,1.00,2.00,3.00,4.0,5,6.00,7.00,8.00,9.00,10.00,11.00,12.00,13
1,0.0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
2,1.0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
3,2.0,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
4,3.0,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480

In [23]:
# df = pd.read_html('https://en.wikipedia.org/wiki/Mobile_country_code',match='Country',header =0)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,NaN,0,1.00,2.00,3.00,4.0,5,6.00,7.00,8.00,9.00,10.00,11.00,12.00,13
1,0.0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
2,1.0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
3,2.0,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
4,3.0,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480

In [28]:
df_excel = pd.read_excel('data.xlsx')

In [29]:
df_excel.to_pickle('df_excel')

In [30]:
pd.read_pickle('df_excel')

    Name  Age
0  Krish   32
1   Jack   34
2   John   31