In [5]:
import pandas as pd

data = [1,2,3,4,5,6,7,8,9,10]
series = pd.Series(data)
print(series)
print(type(series))

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
<class 'pandas.core.series.Series'>

In [6]:
# create series from the dictionary
data_dict = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
series_dict = pd.Series(data_dict)
print(series_dict)

a    1
b    2
c    3
d    4
dtype: int64

In [7]:
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data, index=index)
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [23]:
# Create a dictionary of lists for the dataframe
data_for_df = {
  'name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
  'age': [25, 30, 35, 28, 32],
  'city': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
  'occupation': ['Engineer', 'Doctor', 'Teacher', 'Designer', 'Manager'],
  'salary': [75000, 120000, 55000, 65000, 85000]
}

# Convert dictionary to dataframe
df_2= pd.DataFrame(data_for_df)
print(df_2)
print(type(df_2))

      name  age         city occupation  salary
0    Alice   25     New York   Engineer   75000
1      Bob   30  Los Angeles     Doctor  120000
2  Charlie   35      Chicago    Teacher   55000
3    Diana   28      Houston   Designer   65000
4      Eve   32      Phoenix    Manager   85000
<class 'pandas.core.frame.DataFrame'>

In [ ]:
import numpy as np
np.array(df_2)

array([['Alice', 25, 'New York', 'Engineer', 75000],
       ['Bob', 30, 'Los Angeles', 'Doctor', 120000],
       ['Charlie', 35, 'Chicago', 'Teacher', 55000],
       ['Diana', 28, 'Houston', 'Designer', 65000],
       ['Eve', 32, 'Phoenix', 'Manager', 85000]], dtype=object)

In [12]:
list_of_dicts = [
  {'name': 'Alice', 'age': 25, 'city': 'New York'},
  {'name': 'Bob', 'age': 30, 'city': 'Los Angeles'},
  {'name': 'Charlie', 'age': 35, 'city': 'Chicago'},
  {'name': 'Diana', 'age': 28, 'city': 'Houston'},
  {'name': 'Eve', 'age': 32, 'city': 'Phoenix'}
]

df = pd.DataFrame(list_of_dicts)
print(df)

      name  age         city
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    Diana   28      Houston
4      Eve   32      Phoenix

In [21]:
df = pd.read_csv('sales.csv')
df.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,255.28,159.42,2533654.00,1582243.50,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,576782.80,328376.44,248406.36
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792,7/5/2014,8102,9.33,6.92,75591.66,56065.84,19525.82
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712,2/6/2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50

In [ ]:
# accessing data from the dataframe
df_2['name']  # Accessing a single column

0      Alice
1        Bob
2    Charlie
3      Diana
4        Eve
Name: name, dtype: object

In [40]:
df_2

      name  age         city occupation  salary
0    Alice   25     New York   Engineer   75000
1      Bob   30  Los Angeles     Doctor  120000
2  Charlie   35      Chicago    Teacher   55000
3    Diana   28      Houston   Designer   65000
4      Eve   32      Phoenix    Manager   85000

In [ ]:
df_2.loc[0]

C:\Users\arthv\AppData\Local\Temp\ipykernel_18688\1405980514.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_2.loc[0][0]

'Alice'

In [34]:
df_2.iloc[0][0]

C:\Users\arthv\AppData\Local\Temp\ipykernel_18688\2647755945.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_2.iloc[0][0]

'Alice'

In [38]:
print(df_2.at[1,'name'])

Bob

In [39]:
print(df_2.iat[1,0])

Bob

In [ ]:
# adding a column to the dataframe
df_2['expence'] = [1000, 2000, 1500, 1800, 2200]

In [42]:
df_2

      name  age         city occupation  salary  expence
0    Alice   25     New York   Engineer   75000     1000
1      Bob   30  Los Angeles     Doctor  120000     2000
2  Charlie   35      Chicago    Teacher   55000     1500
3    Diana   28      Houston   Designer   65000     1800
4      Eve   32      Phoenix    Manager   85000     2200

In [43]:
# remove a column from the dataframe
df_2.drop('expence', axis=1, inplace=True)

In [44]:
df_2

      name  age         city occupation  salary
0    Alice   25     New York   Engineer   75000
1      Bob   30  Los Angeles     Doctor  120000
2  Charlie   35      Chicago    Teacher   55000
3    Diana   28      Houston   Designer   65000
4      Eve   32      Phoenix    Manager   85000

In [45]:
df_2["age"]+=1

In [46]:
df_2

      name  age         city occupation  salary
0    Alice   26     New York   Engineer   75000
1      Bob   31  Los Angeles     Doctor  120000
2  Charlie   36      Chicago    Teacher   55000
3    Diana   29      Houston   Designer   65000
4      Eve   33      Phoenix    Manager   85000

In [47]:
df_2.drop(1, axis=0, inplace=True)

In [48]:
df_2

      name  age      city occupation  salary
0    Alice   26  New York   Engineer   75000
2  Charlie   36   Chicago    Teacher   55000
3    Diana   29   Houston   Designer   65000
4      Eve   33   Phoenix    Manager   85000

In [50]:
df_2.dtypes

name          object
age            int64
city          object
occupation    object
salary         int64
dtype: object

In [51]:
df_2.describe()

             age        salary
count   4.000000      4.000000
mean   31.000000  70000.000000
std     4.396969  12909.944487
min    26.000000  55000.000000
25%    28.250000  62500.000000
50%    31.000000  70000.000000
75%    33.750000  77500.000000
max    36.000000  85000.000000